### ISSUE TITLE
some questions about shufflenet

### ISSUE THREAD

**Issue by ghost** [HolmesShuan/ShuffleNet-An-Extremely-Efficient-CNN-for-Mobile-Devices-Caffe-Reimplementation#1]
1. in shuffle pattern 0, paper said "suppose a convolutional layer with g groups whose output has g × n channels; we first reshape the output channel dimension into (g; n), transposing and then flattening it back as the input of next layer", so I think we should reshape channels not channelxspatial_size.
2. do you train shuffle net? do you understand why use 3x3 avg pooling?
thks

**Comment by HolmesShuan** [comment]
I didn't. This is just our understanding of ShuffleNet. We are still waiting for Zhang's open link. Could u further explain how to reshape channels to `g x n` or `(g;n)`, thanks.  As for avg pooling, just corresponds to DWConV, I guess(with little computation cost).
