### ISSUE TITLE
group parameter

### ISSUE THREAD

**Issue by zhly0** [HolmesShuan/ShuffleNet-An-Extremely-Efficient-CNN-for-Mobile-Devices-Caffe-Reimplementation#2]
hello，holmesShuan，caffe's group parameter can not train using CUDA or cudnn when group>1,when group>1 you have to train using CPU，it is a bug，I don't u have  ever test it or not ?since your implemention have used group  parameter >1sometimes

**Comment by HolmesShuan** [comment]
In `Base_conv_layer.cpp` : 
```CUDA
template <typename Dtype>
void BaseConvolutionLayer<Dtype>::forward_gpu_gemm(const Dtype* input,
    const Dtype* weights, Dtype* output, bool skip_im2col) {
  const Dtype* col_buff = input;
  ...
  for (int g = 0; g < group_; ++g) {
    caffe_gpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, conv_out_channels_ /
        group_, conv_out_spatial_dim_, kernel_dim_,
        (Dtype)1., weights + weight_offset_ * g, col_buff + col_offset_ * g,
        (Dtype)0., output + output_offset_ * g);
  }
}
```
I havn't heard about the bug you mentioned. Please give more details.

**Comment by zhly0** [comment]
you can goto caffe's issue 5612.you will see it

**Comment by HolmesShuan** [comment]
Seems problem solved, right? Although, in my implementation of channel shuffle, I used group parameter but this bug won't exist. U may check my `.cpp` and `.cu`.

**Comment by zhly0** [comment]
the problem is still there.the problem is caused by the cudnn code，I will try your code later
