### ISSUE TITLE
pre-train model

### ISSUE THREAD

**Issue by jinjunbo** [HolmesShuan/ShuffleNet-An-Extremely-Efficient-CNN-for-Mobile-Devices-Caffe-Reimplementation#3]
hello~,I do not know whether it is convenient to share pre-train model ?Thanks!

**Comment by HolmesShuan** [comment]
Sorry, we didn't re-implement ShuffleNet on ImageNet. Please refer to[ FAST-SHUFFLE](https://github.com/farmingyard/ShuffleNet) for more details.
